global using Ivy;
global using Ivy.Apps;
global using Ivy.Auth;
global using Ivy.Chrome;
global using Ivy.Client;
global using Ivy.Core;
global using Ivy.Core.Hooks;
global using Ivy.Helpers;
global using Ivy.Hooks;
global using Ivy.Shared;
global using Ivy.Services;
global using Ivy.Views;
global using Ivy.Views.Alerts;
global using Ivy.Views.Blades;
global using Ivy.Views.Builders;
global using Ivy.Views.Charts;
global using Ivy.Views.Dashboards;
global using Ivy.Views.Forms;
global using Ivy.Views.Tables;
global using Ivy.Views.DataTables;
global using Ivy.Widgets.Inputs;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using System.Collections.Immutable;
global using System.ComponentModel.DataAnnotations;
global using System.Globalization;
global using System.Reactive.Linq;

namespace Frontend;

public record Cohort(string Name, int Version, int Members, string RefreshedDate, string Tag, string[] Blocks, string[] Operators);
public record BackendCohort(int id, string name, string definition, DateTime createdAt);
public record StatsResponse(int totalUsers, int totalCohorts, double avgSize);
public record DistributionItem(string range, int count);
public record CountResponse(int count);
public record TrendItem(string Month, int Cohorts);
public record ActivityItem(string Cohort, string Action, string Timestamp, string User);
public record CreateCohortRequest(string Name, string? Definition, string? AdminUser);
